#!/usr/bin/env python3
"""Generate build.ninja and objdiff.json from config/<version>/.

  config.json   toolchain + compiler flags
  splits.txt    one block per translation unit -> the symbols it owns

Pipeline per translation unit:

    fury.nso --nx2elf--> build/fury.elf --elf_split--> build/target/<u>.o   (expected)
    src/<u>.(c|cpp) --clang--> build/obj/<u>.o                              (actual)

objdiff diffs the two objects.  A unit marked `done` in splits.txt is one whose
compiled object matches; until then it just tracks a match percentage.
"""

from __future__ import annotations

import json
import shlex
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).parent
VERSION = "1.0.0"
CFG = ROOT / "config" / VERSION
PY = Path(sys.executable).as_posix()


SECTIONS = (".text", ".rodata", ".data", ".bss")


@dataclass
class Unit:
    src: str
    ranges: dict[str, tuple[int, int]] = field(default_factory=dict)  # section -> (start, end)
    done: bool = False
    lang: str | None = None            # 'c' | 'c++'
    cflags: str = ""

    @property
    def name(self) -> str:
        return str(Path(self.src).with_suffix("")).replace("\\", "/")

    @property
    def is_cxx(self) -> bool:
        if self.lang:
            return self.lang == "c++"
        return self.src.endswith((".cpp", ".cc", ".cxx", ".C"))

    @property
    def range_args(self) -> list[str]:
        return [f"{s}:{lo:#x}:{hi:#x}" for s, (lo, hi) in self.ranges.items()]


def _parse_range_line(text: str, where: str) -> tuple[str, int, int]:
    # ".text   start:0x123 end:0x456"  /  ".text 0x123 0x456"  /  ".text 0x123-0x456"
    parts = text.replace("-", " ").split()
    sec = parts[0]
    nums = [p.split(":", 1)[-1] for p in parts[1:]]
    if sec not in SECTIONS or len(nums) != 2:
        raise SystemExit(f"{where}: bad range line {text!r} "
                         f"(expected '<section> start:0x.. end:0x..')")
    return sec, int(nums[0], 16), int(nums[1], 16)


def parse_splits(path: Path) -> list[Unit]:
    units: list[Unit] = []
    cur: Unit | None = None
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        where = f"{path}:{lineno}"
        is_header = ":" in line and not line.lstrip().startswith(".")
        if is_header:
            head, _, rest = line.partition(":")
            cur = Unit(src=head.strip())
            for tok in shlex.split(rest.strip()):
                if tok == "done":
                    cur.done = True
                elif tok in ("c", "c++"):
                    cur.lang = tok
                elif tok.startswith("cflags="):
                    cur.cflags = tok[len("cflags="):]
                else:
                    hint = '  (multi-word cflags must be quoted: cflags="-a -b")' if tok.startswith("-") else ""
                    raise SystemExit(f"{where}: unknown option {tok!r}{hint}")
            units.append(cur)
        else:
            if cur is None:
                raise SystemExit(f"{where}: range line before any unit header")
            sec, lo, hi = _parse_range_line(line.strip(), where)
            if hi <= lo:
                raise SystemExit(f"{where}: end 0x{hi:x} <= start 0x{lo:x}")
            cur.ranges[sec] = (lo, hi)
    for u in units:
        if not u.ranges:
            raise SystemExit(f"unit {u.src} has no section ranges")
    return units


def ninja_escape(p: str) -> str:
    return p.replace(":", "$:").replace(" ", "$ ")


def gen_ninja(cfg: dict, units: list[Unit]) -> str:
    tc = cfg["toolchain"]
    fl = cfg["flags"]
    cc = ninja_escape((ROOT / tc["cc"]).resolve().as_posix())
    cxx = ninja_escape((ROOT / tc["cxx"]).resolve().as_posix())
    common = f'--target={tc["target"]} {fl["common"]}'

    L: list[str] = []
    w = L.append
    w("# AUTO-GENERATED by configure.py - edit config/%s/ instead\n" % VERSION)
    w("builddir = build")
    w(f"cflags = {common} {fl['c']}")
    w(f"cxxflags = {common} {fl['cxx']}")
    w("")
    w(f"rule nx2elf\n  command = {PY} tools/nx2elf.py fury.nso -o $out\n  description = nx2elf $out\n")
    w(f"rule split\n  command = {PY} tools/elf_split.py --elf $elf --out $out $ranges\n  description = split $out\n")
    w(f"rule cc\n  command = {cc} $cflags -MD -MF $out.d -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = cc $in\n")
    w(f"rule cxx\n  command = {cxx} $cxxflags -MD -MF $out.d -c $in -o $out\n  depfile = $out.d\n  deps = gcc\n  description = cxx $in\n")
    w("build build/fury.elf: nx2elf | tools/nx2elf.py tools/nso.py fury.nso\n")

    targets: list[str] = []
    for u in units:
        tobj = f"build/target/{u.name}.o"
        aobj = f"build/obj/{u.name}.o"
        ranges = " ".join("--range " + r for r in u.range_args)
        w(f"build {tobj}: split build/fury.elf | tools/elf_split.py tools/elfobj.py tools/furyimg.py")
        w(f"  elf = build/fury.elf")
        w(f"  ranges = {ranges}")
        rule = "cxx" if u.is_cxx else "cc"
        w(f"build {aobj}: {rule} {u.src}")
        if u.cflags:
            key = "cxxflags" if u.is_cxx else "cflags"
            base = fl["cxx"] if u.is_cxx else fl["c"]
            w(f"  {key} = {common} {base} {u.cflags}")
        w("")
        targets += [tobj, aobj]

    w("build all: phony " + " ".join(targets))
    w("default all")
    return "\n".join(L) + "\n"


def gen_objdiff(units: list[Unit]) -> dict:
    return {
        "min_version": "3.0.0",
        "custom_make": "ninja",
        "build_target": True,
        "build_base": True,
        "watch_patterns": ["*.c", "*.cpp", "*.cc", "*.h", "*.hpp",
                           "tools/*.py", "config/**/*"],
        "units": [{
            "name": u.name,
            "target_path": f"build/target/{u.name}.o",
            "base_path": f"build/obj/{u.name}.o",
            "metadata": {"source_path": u.src, "complete": u.done},
        } for u in units],
    }


def main():
    cfg = json.loads((CFG / "config.json").read_text())
    units = parse_splits(CFG / "splits.txt")
    (ROOT / "build.ninja").write_text(gen_ninja(cfg, units))
    (ROOT / "objdiff.json").write_text(json.dumps(gen_objdiff(units), indent=2) + "\n")
    done = sum(u.done for u in units)
    print(f"configured {len(units)} unit(s), {done} done -> build.ninja, objdiff.json")


if __name__ == "__main__":
    main()
