#pragma once

#include <basis/seadTypes.h>
#include "System/GameDataHolderAccessor.hpp"
#include "System/GameDataHolderWriter.hpp"

namespace al {
class GameDataHolderBase;
class IUseSceneObjHolder;
class SceneObjHolder;
} // namespace al
class StageDatabaseInfo;
class WorldInfo;

namespace GameDataFunction {
GameDataHolder* getGameDataHolder(const al::IUseSceneObjHolder* pUser);
GameDataHolder* getGameDataHolder(const al::SceneObjHolder* pHolder);
GameDataHolder* getGameDataHolder(al::GameDataHolderBase* pHolder);
void setSaveRequested(GameDataHolderWriter writer, bool isRequested);
bool isSaveRequested(GameDataHolderAccessor accessor);
void updatePlayerFigures(GameDataHolderWriter writer, int figureType);
void initTotalPlayTimeSM(GameDataHolderAccessor accessor, int fileId);
s64 getTotalPlayTimeSM(GameDataHolderAccessor accessor, bool isIncludeCurrentPlay);
void setTotalPlayTimeSM(GameDataHolderAccessor accessor);
void initTotalPlayTimeOG(GameDataHolderAccessor accessor, int fileId);
s64 getTotalPlayTimeOG(GameDataHolderAccessor accessor, bool isIncludeCurrentPlay);
void setTotalPlayTimeOG(GameDataHolderAccessor accessor);
bool isInvalidCourseId(int courseId);
int getInvalidCourseId();
int getPlayerLife(GameDataHolderAccessor accessor);
int addPlayerLife(GameDataHolderWriter writer, int life);
bool isGameOver(GameDataHolderAccessor accessor);
const char* getPlayerCharacterNameFromBitFlag(GameDataHolderAccessor accessor, u32 flag);
void onStartTitleScene(GameDataHolderWriter writer);
void onEndTitleScene(GameDataHolderWriter writer);
void recoverGameOver(GameDataHolderWriter writer);
void recoverGameOverFromGoldenExpress(GameDataHolderWriter writer);
void startStage(GameDataHolderWriter writer, int worldId, int stageId);
void startSingleModeStage(GameDataHolderWriter writer, int worldId, int stageId);
void onStageStart(GameDataHolderWriter writer);
void onStageEnd(GameDataHolderWriter writer);
void onSaveStartInCourseSelect(GameDataHolderWriter writer);
void onWorldWarp(GameDataHolderWriter writer, int worldId);
void onWorldWarpDokanDemo(GameDataHolderWriter writer);
void onGotoTitle(GameDataHolderWriter writer, int worldId);
void clearStage(GameDataHolderWriter writer);
void clearStageWorldWarp(GameDataHolderWriter writer);
void retireStage(GameDataHolderWriter writer);
void retireStageExitDoor(GameDataHolderWriter writer);
void restartStage(GameDataHolderWriter writer);
void resetStageScore(GameDataHolderWriter writer);
void restartKinopioBrigade(GameDataHolderWriter writer);
void restartMysteryBox(GameDataHolderWriter writer);
void restartTimeupMysteryBox(GameDataHolderWriter writer);
void reenterStage(GameDataHolderWriter writer);
void playWorldStartDemo(GameDataHolderWriter writer, int worldId);
void updateBestScoreUser(GameDataHolderWriter writer);
void setBestScoreUserId(GameDataHolderWriter writer, int userId);
void playReportStageEvent(GameDataHolderWriter writer, int eventId);
void playReportOptionsEvent(GameDataHolderWriter writer);
void incMenuRestartCount(GameDataHolderWriter writer);
void stockItem(GameDataHolderWriter writer, int itemId);
int getStockItem(GameDataHolderAccessor accessor, int index);
int getStockItemInCourseSelect(GameDataHolderAccessor accessor, int index);
void useStockItem(GameDataHolderWriter writer);
int getTopItem(GameDataHolderAccessor accessor);
void addCoin(GameDataHolderWriter writer, int count);
int getCoinNum(GameDataHolderAccessor accessor);
int getTotalScore(GameDataHolderAccessor accessor);
int getUserScore(GameDataHolderAccessor accessor, int userId);
int getWorldNum(GameDataHolderAccessor accessor);
int getCourseTotalNum(GameDataHolderAccessor accessor);
int calcCourseId(GameDataHolderAccessor accessor, int worldId, int stageId);
int tryCalcCourseId(GameDataHolderAccessor accessor, int worldId, int stageId);
int calcStartFairyPrincessLeaveCastleCourseId(GameDataHolderAccessor accessor);
int findKoopaCastleCourseId(GameDataHolderAccessor accessor, int worldId);
int calcRosettaAppearanceCourseId(GameDataHolderAccessor accessor);
int calcOpenNetworkSettingCourseId(GameDataHolderAccessor accessor);
int calcOpenWorldArrangeCourseId(GameDataHolderAccessor accessor);
int calcShowWorldJumpMenuInfoCourseId(GameDataHolderAccessor accessor);
int calcShowWorldJumpMenuInfo2ndCourseId(GameDataHolderAccessor accessor);
int calcShowCharacterChangeExplainCourseId(GameDataHolderAccessor accessor);
int calcShowNetworkGuideCourseId(GameDataHolderAccessor accessor);
int calcShowAmiiboGuideCourseId(GameDataHolderAccessor accessor);
int calcShowSnapshotGuideCourseId(GameDataHolderAccessor accessor);
int calcShowTouchGuideCourseId(GameDataHolderAccessor accessor);
void calcWorldAndStageId(GameDataHolderAccessor accessor, int* pWorldId, int* pStageId,
                         int courseId);
StageDatabaseInfo* findStageDatabaseInfo(GameDataHolderAccessor accessor, int courseId);
WorldInfo* findWorldInfo(GameDataHolderAccessor accessor, int worldId);
int findCourseLockGreenStarNum(GameDataHolderAccessor accessor, int courseId);
int findCourseGreenStarNum(GameDataHolderAccessor accessor, int courseId);
int calcWorldCourseNum(GameDataHolderAccessor accessor, int worldId);
const char* getStageNameFromWorld(GameDataHolderAccessor accessor, int worldId, int index);
int tryFindWorldIdFromStageName(GameDataHolderAccessor accessor, const char* pStageName);
bool isEnableShowBestTimeStage(GameDataHolderAccessor accessor, int courseId);
bool isStageContinuousMysteryBox(GameDataHolderAccessor accessor, int courseId);
bool isCurrentStageKinopioBrigade(GameDataHolderAccessor accessor);
int getPlayingCourseId(GameDataHolderAccessor accessor);
bool isStageKinopioBrigade(GameDataHolderAccessor accessor, int courseId);
bool isCurrentStageGateKeeper(GameDataHolderAccessor accessor);
bool isSingleMode(GameDataHolderAccessor accessor);
bool isStageGateKeeper(GameDataHolderAccessor accessor, int courseId);
bool isStageEvent(GameDataHolderAccessor accessor, int courseId);
bool isStageNormal(GameDataHolderAccessor accessor, int courseId);
bool isStageGateKeeperGoalPole(GameDataHolderAccessor accessor, int courseId);
bool isStageGateKeeperNoGoalPole(GameDataHolderAccessor accessor, int courseId);
bool isStageCasinoRoom(GameDataHolderAccessor accessor, int courseId);
bool isStageKinopioHouse(GameDataHolderAccessor accessor, int courseId);
bool isStageKinopioHouseHide(GameDataHolderAccessor accessor, int courseId);
bool isStageFairyHouse(GameDataHolderAccessor accessor, int courseId);
bool isStageDokanHide(GameDataHolderAccessor accessor, int courseId);
bool isStageUseDrc(GameDataHolderAccessor accessor, int courseId);
bool isStageGoldenExpress(GameDataHolderAccessor accessor, int courseId);
bool isStageKoopaCastle(GameDataHolderAccessor accessor, int courseId);
bool isStageKoopaCastleNormal(GameDataHolderAccessor accessor, int courseId);
bool isStageKoopaCastleTank(GameDataHolderAccessor accessor, int courseId);
bool isStageKoopaCastleExpress(GameDataHolderAccessor accessor, int courseId);
bool isStageKoopaCastleExpressNormal(GameDataHolderAccessor accessor, int courseId);
bool isStageKoopaCastleFortress(GameDataHolderAccessor accessor, int courseId);
bool isStageChampionShip(GameDataHolderAccessor accessor, int courseId);
bool isStageLastPlay(GameDataHolderAccessor accessor, int courseId);
int getLastPlayCourseId(GameDataHolderAccessor accessor);
bool isStageLastPlayAndFirstClear(GameDataHolderAccessor accessor, int courseId);
bool isLastPlayCourseFirstClear(GameDataHolderAccessor accessor);
const char* findStageName(GameDataHolderAccessor accessor, int courseId);
bool isStageNoCourseName(GameDataHolderAccessor accessor, int courseId);
int getLastKoopaCourseId(GameDataHolderAccessor accessor);
int getLastKoopaGK1CourseId(GameDataHolderAccessor accessor);
int getLastKoopaGK2CourseId(GameDataHolderAccessor accessor);
int getLastSingleModePlayingFileID(GameDataHolderAccessor accessor);
int calcPlayingWorldId(GameDataHolderAccessor accessor);
bool isLastPlayCourseClear(GameDataHolderAccessor accessor);
bool isLastPlayCourseClearWorldWarp(GameDataHolderAccessor accessor);
bool isLastPlayCourseFirstAcquireIllustItem(GameDataHolderAccessor accessor);
bool isLastPlayCourseUpdateBestScore(GameDataHolderAccessor accessor);
bool isLastPlayCourseUpdateBestTime(GameDataHolderAccessor accessor);
bool isNeedSave(GameDataHolderAccessor accessor);
bool isNeedOpenCasinoRoom(GameDataHolderAccessor accessor);
bool isNeedOpenGoldenExpress(GameDataHolderAccessor accessor);
void resetCasinoRoomCounter(GameDataHolderWriter writer);
int tryGetLastStageBestScoreUserID(GameDataHolderAccessor accessor);
void updateClearStarLevel(GameDataHolderWriter writer);
bool isEnableClearCharacterInfo(GameDataHolderAccessor accessor);
bool isEnableBestTimeInfo(GameDataHolderAccessor accessor);
bool isEnableSpecialWorld(GameDataHolderAccessor accessor);
bool isEnableFlagGoldStar(GameDataHolderAccessor accessor);
int calcOpenWorldIdMax(GameDataHolderAccessor accessor);
int calcOpenWorldIdMaxAllFile(GameDataHolderAccessor accessor);
int getMissCount(GameDataHolderAccessor accessor);
void addMissCount(GameDataHolderWriter writer);
bool isClearWithAssistBlock(GameDataHolderAccessor accessor);
void setUseAssistBlock(GameDataHolderWriter writer);
bool isIsInsideSuperbView(GameDataHolderAccessor accessor);
void setIsInsideSuperbView(GameDataHolderWriter writer);
void resetIsInsideSuperbView(GameDataHolderWriter writer);
void acquireGreenStar(GameDataHolderWriter writer, int starIndex);
bool isAcquireGreenStar(GameDataHolderAccessor accessor, int starIndex);
bool isAcquireGreenStarAll(GameDataHolderAccessor accessor);
int calcTotalAcquireGreenStarNum(GameDataHolderAccessor accessor);
int getLastTotalAcquireGreenStarNum(GameDataHolderAccessor accessor);
int findIllustItemNum(GameDataHolderAccessor accessor, int courseId);
void acquireIllustItem(GameDataHolderWriter writer);
void setStampPickupCharType(GameDataHolderWriter writer, int characterType);
int calcTotalIllustItemNum(GameDataHolderAccessor accessor);
bool isAcquireIllustItem(GameDataHolderAccessor accessor);
bool isAcquireCharacterCompleteIllustItem(GameDataHolderAccessor accessor, int characterType,
                                          bool isCheckFile, int fileId);
int findGhostStageSerialId(GameDataHolderAccessor accessor, int courseId);
int calcGhostStageNumInWorld(GameDataHolderAccessor accessor, int worldId);
int getGhostPresentCounter(GameDataHolderAccessor accessor);
int findGhostBaseTime(GameDataHolderAccessor accessor, const char* pStageName);
int getDoubleMarioNumMax(GameDataHolderAccessor accessor);
void setNetworkSettingInit(GameDataHolderWriter writer, bool isInit);
void setMiiverseSetting(GameDataHolderWriter writer, int setting);
void setGhostSetting(GameDataHolderWriter writer, int setting);
int getMiiverseSetting(GameDataHolderAccessor accessor);
bool isEnableMiiverse(GameDataHolderAccessor accessor);
int getGhostSetting(GameDataHolderAccessor accessor);
bool setCameraReverseVertical(GameDataHolderWriter writer, bool isReverse);
bool getCameraReverseVertical(GameDataHolderWriter writer);
bool setCameraReverseHorizontal(GameDataHolderWriter writer, bool isReverse);
bool getCameraReverseHorizontal(GameDataHolderWriter writer);
void setKinopioBrigadeCameraReverseVertical(GameDataHolderWriter writer, bool isReverse);
bool getKinopioBrigadeCameraReverseVertical(GameDataHolderWriter writer);
void setKinopioBrigadeCameraReverseHorizontal(GameDataHolderWriter writer, bool isReverse);
bool getKinopioBrigadeCameraReverseHorizontal(GameDataHolderWriter writer);
int getInitStageTimer(GameDataHolderAccessor accessor);
void turnBackStageTimer(GameDataHolderWriter writer, int count);
void resetCheckpointPass(GameDataHolderWriter writer);
void setCheckpointPassMario(GameDataHolderWriter writer);
void setCheckpointPassLuigi(GameDataHolderWriter writer);
void setCheckpointPassPeach(GameDataHolderWriter writer);
void setCheckpointPassKinopio(GameDataHolderWriter writer);
void setCheckpointPassRosetta(GameDataHolderWriter writer);
bool isCheckpointPass(GameDataHolderAccessor accessor);
bool isCheckpointPassMario(GameDataHolderAccessor accessor);
bool isCheckpointPassLuigi(GameDataHolderAccessor accessor);
bool isCheckpointPassPeach(GameDataHolderAccessor accessor);
bool isCheckpointPassKinopio(GameDataHolderAccessor accessor);
bool isCheckpointPassRosetta(GameDataHolderAccessor accessor);
bool isRestartStage(GameDataHolderAccessor accessor);
bool isRestartFromCheckpoint(GameDataHolderAccessor accessor);
bool isSkipStartDemo(GameDataHolderAccessor accessor);
void setSkipStartDemo(GameDataHolderWriter writer, bool isSkip);
void onExistLuigiUSaveData(GameDataHolderWriter writer);
bool isEnablePlayLuigiBros(GameDataHolderAccessor accessor);
bool isAllNewFile(GameDataHolderAccessor accessor);
int getNewFileNum(GameDataHolderAccessor accessor);
int getFirstNewFileId(GameDataHolderAccessor accessor);
int getFileId(GameDataHolderAccessor accessor);
bool isNetworkAccount(GameDataHolderAccessor accessor);
int getAccountSlotNo(GameDataHolderAccessor accessor);
bool isInGameNetworkForbidden(GameDataHolderAccessor accessor);
bool isMiiverseForbidden(GameDataHolderAccessor accessor);
bool isMiiverseReadOnly(GameDataHolderAccessor accessor);
} // namespace GameDataFunction
