#pragma once
#include "System/GameDataHolderAccessor.hpp"
#include "System/GameDataHolderWriter.hpp"

namespace GameDataFlagFunction {
bool isExistNewOpenFlag(GameDataHolderAccessor accessor, bool isExcludeTouchGuide);
bool isShowWorldStartDemo(GameDataHolderAccessor accessor, int worldId);
bool isShowWorldStartDemo(GameDataHolderAccessor accessor, int worldId, int fileId);
void setShowWorldStartDemo(GameDataHolderWriter writer, int worldId);
bool isAfterGameOver(GameDataHolderAccessor accessor);
void resetAfterGameOver(GameDataHolderWriter writer);
bool isAfterEnding(GameDataHolderAccessor accessor);
void resetAfterEnding(GameDataHolderWriter writer);
const char* tryGetFirstNewOpenFlagMessageLabelByStageClear(GameDataHolderAccessor accessor);
bool isNewOpenAllClearCharacter(GameDataHolderAccessor accessor, int characterType);
bool isNewOpenShowBestTime(GameDataHolderAccessor accessor);
bool isNewOpenRosetta(GameDataHolderAccessor accessor);
bool isNewOpenArrangeWorld(GameDataHolderAccessor accessor);
bool isNewOpenChampionshipWorld(GameDataHolderAccessor accessor);
bool isNewShowWorldJumpMenuInfo(GameDataHolderAccessor accessor);
bool isNewShowWorldJumpMenuInfo2nd(GameDataHolderAccessor accessor);
bool isNewFirstClearKinopioBrigade(GameDataHolderAccessor accessor);
bool isNewShowCharacterChangeExplain(GameDataHolderAccessor accessor);
bool isNewFirstClearDrcTouchStage(GameDataHolderAccessor accessor);
bool isNewShowAfterGameOverInfo(GameDataHolderAccessor accessor);
bool isNewShowNetworkGuide(GameDataHolderAccessor accessor);
bool isNewShowAmiiboGuide(GameDataHolderAccessor accessor);
bool isNewShowSnapshotGuide(GameDataHolderAccessor accessor);
void setFirstAlreadyOpenFlagByStageClear(GameDataHolderWriter writer);
void setAllClearCharacter(GameDataHolderWriter writer, int characterType);
void setOpenShowBestTime(GameDataHolderWriter writer);
void setOpenRosetta(GameDataHolderWriter writer);
void setOpenArrangeWorld(GameDataHolderWriter writer);
void setOpenChampionshipWorld(GameDataHolderWriter writer);
void setShowWorldJumpMenuInfo(GameDataHolderWriter writer);
void setShowWorldJumpMenuInfo2nd(GameDataHolderWriter writer);
void setFirstClearKinopioBrigade(GameDataHolderWriter writer);
void setShowCharacterChangeExplain(GameDataHolderWriter writer);
void setFirstClearDrcTouchStage(GameDataHolderWriter writer);
void setShowAfterGameOverInfo(GameDataHolderWriter writer);
void setShowNetworkGuide(GameDataHolderWriter writer);
void setShowAmiiboGuide(GameDataHolderWriter writer);
void setShowSnapshotGuide(GameDataHolderWriter writer);
bool isAlreadyOpenAllClearCharacter(GameDataHolderAccessor accessor, int characterType);
bool isAlreadyOpenAllClearCharacter(GameDataHolderAccessor accessor, int characterType,
                                    int fileId);
bool isAlreadyOpenRosetta(GameDataHolderAccessor accessor);
bool isAlreadyOpenShowBestTime(GameDataHolderAccessor accessor);
bool isAlreadyOpenArrangeWorld(GameDataHolderAccessor accessor);
bool isAlreadyOpenChampionshipWorld(GameDataHolderAccessor accessor);
bool isAlreadyShowWorldJumpMenuInfo(GameDataHolderAccessor accessor);
bool isAlreadyShowWorldJumpMenuInfo2nd(GameDataHolderAccessor accessor);
bool isAlreadyFirstClearKinopioBrigade(GameDataHolderAccessor accessor);
bool isAlreadyShowAfterGameOverInfo(GameDataHolderAccessor accessor);
bool isAlreadyShowNetworkGuide(GameDataHolderAccessor accessor);
bool isAlreadyShowAmiiboGuide(GameDataHolderAccessor accessor);
bool isAlreadyShowSnapshotGuide(GameDataHolderAccessor accessor);
bool isNewShowTouchGuide(GameDataHolderAccessor accessor);
bool isAlreadyShowTouchGuide(GameDataHolderAccessor accessor);
void setShowTouchGuide(GameDataHolderWriter writer);
bool isAlreadyShowCharacterChangeExplain(GameDataHolderAccessor accessor);
bool isNewOpenNetworkSetting(GameDataHolderAccessor accessor);
bool isAlreadyOpenNetworkSetting(GameDataHolderAccessor accessor);
void setOpenNetworkSetting(GameDataHolderWriter writer);
bool isAlreadyFirstClearDrcTouchStage(GameDataHolderAccessor accessor);
bool isAlreadyShowSpecialWorldOpenDemo(GameDataHolderAccessor accessor);
void setShowSpecialWorldOpenDemo(GameDataHolderWriter writer);
bool isAlreadyPlayKinopioBrigade(GameDataHolderAccessor accessor);
void setPlayKinopioBrigade(GameDataHolderWriter writer);
bool isAlreadyPlayCasinoRoom(GameDataHolderAccessor accessor);
void setPlayCasinoRoom(GameDataHolderWriter writer);
bool isAlreadyPlayRidon(GameDataHolderAccessor accessor);
void setPlayRidon(GameDataHolderWriter writer);
void resetPlayRidon(GameDataHolderWriter writer);
bool isAlreadyOpenCourseSelectRocket(GameDataHolderAccessor accessor);
void setOpenCourseSelectRocket(GameDataHolderWriter writer);
bool isAlreadyFirstLaunchCourseSelectRocket(GameDataHolderAccessor accessor);
void setFirstLaunchCourseSelectRocket(GameDataHolderWriter writer);
bool isAlreadyShowEventGateKeeperFirst(GameDataHolderAccessor accessor);
void setShowEventGateKeeperFirst(GameDataHolderWriter writer);
bool isAlreadyShowEventGateKeeperSecond(GameDataHolderAccessor accessor);
void setShowEventGateKeeperSecond(GameDataHolderWriter writer);
bool isAlreadyPlayMysteryHouse(GameDataHolderAccessor accessor);
void setPlayMysteryHouse(GameDataHolderWriter writer);
bool isAlreadyRetryMysteryHouse(GameDataHolderAccessor accessor);
void setRetryMysteryHouse(GameDataHolderWriter writer);
bool isAlreadyPlayKinopioHouse(GameDataHolderAccessor accessor);
void setPlayKinopioHouse(GameDataHolderWriter writer);
bool isLeaveCastleFairyPrincess(GameDataHolderAccessor accessor);
bool isEnableDemoLeaveCastleFairyPrincess(GameDataHolderAccessor accessor, int worldId);
bool isEnableShowCourseSelectRocketRock(GameDataHolderAccessor accessor);
} // namespace GameDataFlagFunction
