#!/usr/bin/env python3
"""Generate the translation-unit list in config/<ver>/splits.txt from the
function map (config/<ver>/function_map.tsv).

splits.txt has two parts:

  * hand-maintained units at the top - never touched by this tool;
  * everything after the GENERATED marker line, rewritten on every run: one
    unit per object in the function map, with its .text range.

Options on a generated unit's header (`done`, `cflags=...`) survive a rerun.
Functions claimed by a hand-maintained unit are removed from the generated
ones (a generated unit that ends up non-contiguous is split into `_2`, `_3`...).
To take a unit over by hand, move its block above the marker.

Source paths:
  game folders            src/Game/<Folder>/<Object>.cpp
  al (Library/, Project/) src/al/<Folder>/<Object>.cpp
  sead / agl / eui        src/<lib>/<Object>.cpp
  NintendoWare/<x>        src/nw/<x>/<Object>.cpp
  anything else           src/<Folder>/<Object>.cpp

    python tools/gen_splits.py        # then: python configure.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from furyimg import FuryImage, BASE  # noqa: E402

MARKER = "# ==== GENERATED by tools/gen_splits.py from function_map.tsv - everything below is rewritten ===="
SKIP_FOLDERS = {".dynlink"}


def src_path(folder: str, obj: str, is_c: bool) -> str:
    stem = obj[:-2] if obj.endswith(".o") else obj
    stem = re.sub(r"[^A-Za-z0-9_.+-]", "_", stem)
    ext = ".c" if is_c else ".cpp"
    f = folder.strip("/")
    if f.startswith(("Library", "Project")):
        base = f"src/al/{f}"
    elif f in ("sead", "agl", "eui", "erepo", "aal"):
        base = f"src/{f}"
    elif f.startswith("NintendoWare/"):
        base = "src/nw/" + f.split("/", 1)[1]
    elif f.startswith("NintendoSDK/NintendoWare/"):
        base = "src/nw/" + f.split("/", 2)[2]
    else:
        base = f"src/Game/{f}"
    return f"{base}/{stem}{ext}"


def read_map(path: str):
    rows = []
    with open(path, encoding="utf-8") as fh:
        header = fh.readline().rstrip("\n").split("\t")
        for line in fh:
            c = line.rstrip("\n").split("\t")
            c += [""] * (6 - len(c))
            rows.append((int(c[0], 16) - BASE, c[1].strip(), c[2].strip(), c[4].strip()))
    return rows


def parse_existing(text: str):
    """-> (manual text, {src: header options} of generated units, manual ranges)"""
    manual, gen = text, ""
    if MARKER in text:
        manual, gen = text.split(MARKER, 1)
    opts = {}
    for line in gen.splitlines():
        s = line.split("#", 1)[0].rstrip()
        if s and not s.startswith((" ", "\t")) and ":" in s:
            head, _, rest = s.partition(":")
            opts[head.strip()] = rest.strip()
    claimed = []
    cur = None
    for line in manual.splitlines():
        s = line.split("#", 1)[0].rstrip()
        if not s.strip():
            continue
        if not s.startswith((" ", "\t")) and ":" in s:
            cur = s.split(":", 1)[0].strip()
            continue
        parts = s.replace("-", " ").split()
        if cur and parts and parts[0] == ".text" and len(parts) == 3:
            lo = int(parts[1].split(":")[-1], 16)
            hi = int(parts[2].split(":")[-1], 16)
            claimed.append((lo, hi, cur))
    return manual.rstrip() + "\n", opts, claimed


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--version", default="1.0.0")
    ap.add_argument("--elf", default="build/fury.elf")
    a = ap.parse_args(argv)

    cfg = Path("config") / a.version
    fmap = cfg / "function_map.tsv"
    splits = cfg / "splits.txt"
    rows = read_map(str(fmap))
    img = FuryImage(a.elf, extra_map=str(fmap))
    text_lo, text_hi = img.ranges[".text"]

    manual, opts, claimed = parse_existing(splits.read_text() if splits.exists() else "")

    def is_claimed(addr):
        return any(lo <= addr < hi for lo, hi, _ in claimed)

    def fn_end(addr):
        best = 0
        for s in img.syms_at(addr):
            if s.section == ".text":
                best = max(best, s.size)
        return addr + best

    # group rows into (folder, object) runs, in address order
    units = []   # [folder, obj, [addrs], all_c]
    folder = obj = None
    for addr, f, o, name in rows:
        if f:
            folder, obj = f, None
        if o:
            obj = o
            units.append([folder, obj, [], True])
        if obj is None or folder in SKIP_FOLDERS or not (text_lo <= addr < text_hi):
            continue
        u = units[-1]
        u[2].append(addr)
        if name.startswith("_Z"):
            u[3] = False

    out_units = []
    seen_src = set()
    for folder, obj, addrs, all_c in units:
        if not addrs or folder in SKIP_FOLDERS:
            continue
        # contiguous pieces not claimed by a manual unit
        pieces, cur = [], []
        for ad in addrs:
            if is_claimed(ad):
                if cur:
                    pieces.append(cur)
                cur = []
                continue
            cur.append(ad)
        if cur:
            pieces.append(cur)
        base = src_path(folder, obj, all_c)
        for n, piece in enumerate(pieces):
            src = base if n == 0 else re.sub(r"(\.\w+)$", rf"_{n + 1}\1", base)
            k = 2
            while src in seen_src:
                src = re.sub(r"(\.\w+)$", rf"_dup{k}\1", base)
                k += 1
            seen_src.add(src)
            lo = piece[0]
            hi = max(fn_end(x) for x in piece[-3:]) if piece else lo
            hi = max(hi, lo + 4)
            out_units.append((src, lo, hi))

    lines = [manual.rstrip(), "", MARKER, ""]
    for src, lo, hi in out_units:
        o = opts.get(src, "")
        lines.append(f"{src}:{(' ' + o) if o else ''}")
        lines.append(f"    .text   start:0x{lo:08X} end:0x{hi:08X}")
    splits.write_text("\n".join(lines) + "\n")
    print(f"{len(out_units)} generated unit(s) + {len(claimed)} hand-maintained -> {splits}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
