#!/usr/bin/env python3
"""Measure progress with objdiff and write it into README.md.

    python tools/progress.py            # ninja all + report + update README.md
    python tools/progress.py --no-build # use the objects already in build/
    python tools/progress.py --print    # just print the table

Runs `ninja all` (every unit carved, every source compiled), then
`objdiff-cli report generate` into build/report.json, and replaces the text
between the PROGRESS markers in README.md with a table per library.

"Matched code" is objdiff's measure: bytes of functions that match (objdiff's
report does not compare relocation targets; tools/diff.py does).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
REPORT = ROOT / "build" / "report.json"
START = "<!-- PROGRESS:START (generated by tools/progress.py - do not edit) -->"
END = "<!-- PROGRESS:END -->"

ORDER = [
    ("game", "Game (RedCarpet)"),
    ("al", "ActionLibrary (al)"),
    ("sead", "sead"),
    ("agl", "agl"),
    ("eui", "eui"),
    ("nw", "NintendoWare"),
    ("other", "Other"),
]


def objdiff_cli() -> str:
    for cand in (ROOT / "tools/bin/objdiff-cli.exe", ROOT / "tools/bin/objdiff-cli"):
        if cand.is_file():
            return str(cand)
    exe = shutil.which("objdiff-cli")
    if exe:
        return exe
    raise SystemExit("objdiff-cli not found (put it in tools/bin/ or on PATH)")


def build() -> None:
    subprocess.run([sys.executable, "configure.py"], cwd=ROOT, check=True, stdout=subprocess.DEVNULL)
    subprocess.run(["ninja", "all"], cwd=ROOT, check=True, stdout=subprocess.DEVNULL)


def report() -> dict:
    REPORT.parent.mkdir(exist_ok=True)
    subprocess.run([objdiff_cli(), "report", "generate", "-o", str(REPORT), "-f", "json"],
                   cwd=ROOT, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return json.loads(REPORT.read_text())


def n(v) -> int:
    return int(v or 0)


def pct(a: int, b: int) -> str:
    return f"{100.0 * a / b:.3f}%" if b else "-"


def table(rep: dict) -> str:
    cats = {c["id"]: c["measures"] for c in rep.get("categories", [])}
    units = {}
    for u in rep.get("units", []):
        for cid in (u.get("metadata", {}) or {}).get("progress_categories", []) or []:
            units.setdefault(cid, [0, 0])
            units[cid][1] += 1
            if (u.get("metadata", {}) or {}).get("complete"):
                units[cid][0] += 1
    rows = ["| Library | Code matched | Bytes | Functions | Units done |",
            "|---|---:|---:|---:|---:|"]
    for cid, label in ORDER:
        m = cats.get(cid)
        if not m:
            continue
        tc, mc = n(m.get("total_code")), n(m.get("matched_code"))
        tf, mf = n(m.get("total_functions")), n(m.get("matched_functions"))
        ud, ut = units.get(cid, [0, 0])
        rows.append(f"| {label} | {pct(mc, tc)} | {mc:,} / {tc:,} | {mf:,} / {tf:,} | {ud} / {ut} |")
    m = rep["measures"]
    tc, mc = n(m.get("total_code")), n(m.get("matched_code"))
    tf, mf = n(m.get("total_functions")), n(m.get("matched_functions"))
    rows.append(f"| **Total** | **{pct(mc, tc)}** | {mc:,} / {tc:,} | {mf:,} / {tf:,} | "
                f"{n(m.get('complete_units'))} / {n(m.get('total_units'))} |")
    return "\n".join(rows)


def update_readme(tbl: str) -> bool:
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit(f"README.md has no {START} ... {END} block")
    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    new = f"{head}{START}\n{tbl}\n{END}{tail}"
    if new != text:
        README.write_text(new, encoding="utf-8")
        return True
    return False


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-build", action="store_true")
    ap.add_argument("--print", action="store_true", help="print the table, don't touch README.md")
    a = ap.parse_args(argv)
    if not a.no_build:
        build()
    tbl = table(report())
    if a.print:
        print(tbl)
    else:
        changed = update_readme(tbl)
        print(tbl)
        print("README.md updated" if changed else "README.md already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
